- name: Add Git upstream repository
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: true
  become: true

- name: Install git
  ansible.builtin.apt:
    name: git
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Set global Git credential helper
  ansible.builtin.git_config:
    scope: global
    name: credential.helper
    value: "/mnt/c/Program\\ Files/Git/mingw64/bin/git-credential-manager.exe"
  become: true
  become_user: "{{ username }}"

- name: Set global Git credential helper ADO
  ansible.builtin.git_config:
    scope: global
    name: credential.https://dev.azure.com.useHttpPath
    value: true
  become: true
  become_user: "{{ username }}"
