- name: Add hasicorp key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Add hasicorp repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    update_cache: true
  become: true

- name: Install terraform
  ansible.builtin.apt:
    name:
      - terraform
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Set alias for Terraform ('tf' command) for all users
  ansible.builtin.lineinfile:
    path: /etc/profile.d/terraform.sh
    line: 'alias tf="terraform"'
    create: yes
  become: yes

- name: Set Terraform autocomplete for 'tf' alias for all users
  ansible.builtin.lineinfile:
    path: /etc/profile.d/terraform.sh
    line: "complete -C /usr/bin/terraform tf"
    create: yes
  become: yes

- name: Check if Terraform autocomplete is already installed
  ansible.builtin.shell:
    cmd: "grep -q 'complete -C /usr/bin/terraform terraform' ~/.bashrc"
  register: autocomplete_check
  ignore_errors: true
  become: true
  become_user: "{{ username }}"

- name: Install Terraform autocomplete for all users
  ansible.builtin.shell:
    cmd: "terraform -install-autocomplete"
  when: autocomplete_check.rc != 0
  become: true
  become_user: "{{ username }}"
