- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Install common packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
      - dnsutils
      - xdg-utils
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Create directory keys
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
